import { GalleryItem, FilterTag } from '@/types/gallery';

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: 1,
    title: 'Reinforcement Steel Bindings',
    category: 'products',
    imageUrl: '/images/gallery/steel-bindings.jpg',
    description: 'Coils and wire bindings ready for concrete reinforcement.',
  },
  {
    id: 2,
    title: 'Colour Coated Corrugated Sheets',
    category: 'products',
    imageUrl: '/images/products/roofing-sheets.jpg',
    description: 'Finished orange and galvanized roofing sheets stacked at the forming line.',
  },
  {
    id: 3,
    title: 'Raw TMT Rebars',
    category: 'products',
    imageUrl: '/images/gallery/tmt-rebars.jpg',
    description: 'Bundles of high-ductility rebar reinforcement rods stored on outdoor runners.',
  },
  {
    id: 4,
    title: 'Hollow Pipe Sections',
    category: 'warehouse',
    imageUrl: '/images/gallery/steel-pipes.jpg',
    description: 'Square and circular structural steel tubes organized on storage racks.',
  },
  {
    id: 5,
    title: 'Hollow Square Pipes',
    category: 'warehouse',
    imageUrl: '/images/gallery/square-pipes.jpg',
    description: 'Heavy structural square sections stacked on the fabrication workshop floor.',
  },
  {
    id: 6,
    title: 'Outdoor Storage Yard',
    category: 'facility',
    imageUrl: '/images/gallery/storage-yard.jpg',
    description: 'Rebar coils and raw reinforcement rods staged in the secure loading yard.',
  },
  {
    id: 7,
    title: 'Facility Entrance Gate',
    category: 'facility',
    imageUrl: '/images/gallery/facility-entrance.jpg',
    description: 'Access gateway to the manufacturing and dispatch yards.',
  },
  {
    id: 8,
    title: 'Manufacturing Plant Facade',
    category: 'facility',
    imageUrl: '/images/gallery/plant-facade.jpg',
    description: 'Main structural fabrication unit housing advanced slitting and corrugated rolling mills.',
  },
  {
    id: 9,
    title: 'Warehouse Interior & Commitment Board',
    category: 'warehouse',
    imageUrl: '/images/gallery/warehouse-interior.jpg',
    description: 'Organized product racking, sheets storage, and our core corporate values board.',
  },
  {
    id: 10,
    title: 'Main Warehouse Ramp & Entrance',
    category: 'facility',
    imageUrl: '/images/gallery/factory-yard-sunset.jpg',
    description: 'Wide concrete ramp leading into the primary manufacturing and storage division.',
  },
  {
    id: 11,
    title: 'Yard TMT Rebar Bundles',
    category: 'warehouse',
    imageUrl: '/images/gallery/factory-rebar-view.jpg',
    description: 'Raw high-ductility steel rebar bundles organized on wooden spacers in the yard.',
  },
  {
    id: 12,
    title: 'Secure Operations Gates',
    category: 'facility',
    imageUrl: '/images/gallery/factory-entrance-gate.jpg',
    description: 'Primary transit gates managing dispatch loads and delivery vehicles.',
  },
  {
    id: 13,
    title: 'Hercules Crimping Machine',
    category: 'machinery',
    imageUrl: '/images/gallery/hercules-crimping-machine.jpg',
    description: 'Heavy-duty hydraulic roll forming and tile crimping machinery for roofing sheets.',
  },
  {
    id: 35,
    title: 'Hercules Roll Forming Machine',
    category: 'machinery',
    imageUrl: '/images/gallery/hercules-roll-forming-machine.jpg',
    description: 'Automated high-capacity roll forming mill processing corrugated profile sheets.',
  },
  {
    id: 14,
    title: 'Warehouse Racks & Commitment Board',
    category: 'warehouse',
    imageUrl: '/images/gallery/warehouse-interior-new.jpg',
    description: 'Clean organized inventory racks alongside our corporate client commitment manifesto.',
  },
  {
    id: 15,
    title: 'Overhead Crane & Blue Coils',
    category: 'machinery',
    imageUrl: '/images/gallery/warehouse-crane-blue-coils.jpg',
    description: 'Heavy-duty yellow gantry crane managing raw galvanized blue coil rolls.',
  },
  {
    id: 16,
    title: 'Stacked Structural Square Pipes',
    category: 'warehouse',
    imageUrl: '/images/gallery/square-pipes-stack.jpg',
    description: 'Neatly organized stacks of rectangular hollow steel sections ready for loading.',
  },
  {
    id: 17,
    title: 'Loading Area Hollow Profiles',
    category: 'warehouse',
    imageUrl: '/images/gallery/hollow-sections-warehouse.jpg',
    description: 'Structural steel square tubes stacked adjacent to the delivery dispatch bay.',
  },
  {
    id: 18,
    title: 'Rolling Mill & Sheet Formers',
    category: 'machinery',
    imageUrl: '/images/gallery/factory-floor-worker.jpg',
    description: 'Advanced corrugated roofing sheet profiles rolling line with raw coil feeds.',
  },
  {
    id: 19,
    title: 'Gantry Crane Lift',
    category: 'machinery',
    imageUrl: '/images/gallery/crane-lift-beams.jpg',
    description: 'Precision overhead yellow hoist crane lifting steel sections for distribution.',
  },
  {
    id: 20,
    title: 'Forming Line & Sheet Stacks',
    category: 'machinery',
    imageUrl: '/images/gallery/forming-line-sheets.jpg',
    description: 'Hercules crimper processing orange and blue roofing sheet piles.',
  },
  {
    id: 21,
    title: 'Warehouse Main Transit Corridor',
    category: 'warehouse',
    imageUrl: '/images/gallery/warehouse-interior-main-path.jpg',
    description: 'Wide clear central walkway inside the main fabrication and stock storage facility.',
  },
  {
    id: 22,
    title: 'Sabrang Coated Sheet Rolls',
    category: 'products',
    imageUrl: '/images/gallery/sabrang-sheet-rolls.jpg',
    description: 'Jindal Sabrang brand galvanized color coils and round metal profiles.',
  },
  {
    id: 23,
    title: 'Gantry Crane and Rolling Mills',
    category: 'machinery',
    imageUrl: '/images/gallery/warehouse-full-view.jpg',
    description: 'Perspective view of the factory floor rolling mills beneath the yellow crane.',
  },
  {
    id: 24,
    title: 'Heavy Storage Shelves',
    category: 'warehouse',
    imageUrl: '/images/gallery/shelving-hollow-profiles.jpg',
    description: 'Organized heavy steel racking containing labeled hollow sections.',
  },
  {
    id: 25,
    title: 'Jindal Sabrang Sample Stand',
    category: 'products',
    imageUrl: '/images/gallery/jindal-sabrang-sample-stand.jpg',
    description: 'Jindal Sabrang branded vertical corrugated metal sheets display stand.',
  },
  {
    id: 26,
    title: 'Yellow Gantry Crane System',
    category: 'machinery',
    imageUrl: '/images/gallery/overhead-yellow-crane-yard.jpg',
    description: 'Precision overhead yellow hoist crane lifting steel sections for distribution.',
  },
  {
    id: 27,
    title: 'Warehouse Tube Inventory Racks',
    category: 'warehouse',
    imageUrl: '/images/gallery/warehouse-racks-steel-tubes.jpg',
    description: 'Large stacks of structural hollow steel profiles sorted on storage racks.',
  },
  {
    id: 28,
    title: 'Hercules De-Coiler Machine',
    category: 'machinery',
    imageUrl: '/images/gallery/hercules-decoiler-machine.jpg',
    description: 'Blue Hercules brand metal de-coiler machine processing blue color rolls.',
  },
  {
    id: 29,
    title: 'Jindal Sabrang Blue Color Coated Rolls',
    category: 'products',
    imageUrl: '/images/gallery/jindal-sabrang-blue-coils.jpg',
    description: 'Three large rolls of premium blue color coated sheets.',
  },
  {
    id: 30,
    title: 'Heavy Tube Storage Rack',
    category: 'warehouse',
    imageUrl: '/images/gallery/rack-tubes-blue-tags.jpg',
    description: 'Sorted hollow tubes and pipe bundles with labeled tracking tags on heavy shelving.',
  },
  {
    id: 31,
    title: 'Automated Machinery Console',
    category: 'machinery',
    imageUrl: '/images/gallery/green-machine-control.jpg',
    description: 'Industrial control panel interface alongside a multi-roll steel straightening and bending machine.',
  },
  {
    id: 32,
    title: 'Structural Square Tube Bundles',
    category: 'warehouse',
    imageUrl: '/images/gallery/square-pipes-helmet.jpg',
    description: 'Heavy-duty structural square steel tube stacks staged for dispatch alongside customer safety gear.',
  },
  {
    id: 33,
    title: 'Blue Corrugated Sheet Profiler',
    category: 'machinery',
    imageUrl: '/images/gallery/warehouse-blue-sheets.jpg',
    description: 'Raw blue roofing sheets being processed on the roll forming lines.',
  },
  {
    id: 34,
    title: 'Precision Coil Bender',
    category: 'machinery',
    imageUrl: '/images/gallery/coil-bending-machine.jpg',
    description: 'Automated hydraulic bender unit handling heavy-gauge structural wire and strip profiles.',
  },
];

export const FILTER_TAGS: FilterTag[] = [
  { slug: 'all', name: '🏭 ALL' },
  { slug: 'facility', name: '🏢 FACILITY' },
  { slug: 'warehouse', name: '📦 WAREHOUSE' },
  { slug: 'products', name: '🛠 PRODUCTS' },
  { slug: 'machinery', name: '⚙ MACHINERY' },
  { slug: 'projects', name: '🏗 PROJECTS' },
];
