import { Layers, Cylinder, Wrench, Hammer, Shield } from 'lucide-react';
import { LocalProduct, Category } from '@/types/products';

export const LOCAL_PRODUCTS: LocalProduct[] = [
  {
    id: 'prod-color-galvalume',
    name: 'SSN Aluzinc Premium Roofing Sheet (Sky Blue)',
    slug: 'ssn-color-galvalume',
    category: 'roofing-sheets',
    categoryName: 'Premium Roofing Sheets',
    description: 'High-tensile zinc-aluminium alloy coated steel sheet offering superior corrosion resistance and heat reflectivity.',
    specs: {
      Material: 'Aluminium-Zinc Alloy Coated Steel (55% Al, 43.4% Zn, 1.6% Si)',
      Coating: 'AZ-150 gsm',
      Thickness: '0.40 mm, 0.50 mm',
      Width: 'Customizable',
      Standards: 'IS 15965 / ASTM A792',
    },
    imageUrl: '/images/products/roofing-skyblue.jpg',
  },
  {
    id: 'prod-tile-profile',
    name: 'SSN Aluzinc Premium Roofing Sheet (Turkish Blue)',
    slug: 'ssn-tile-profile',
    category: 'roofing-sheets',
    categoryName: 'Premium Roofing Sheets',
    description: 'High-tensile zinc-aluminium alloy coated steel sheet offering superior corrosion resistance and heat reflectivity.',
    specs: {
      Material: 'Aluminium-Zinc Alloy Coated Steel (55% Al, 43.4% Zn, 1.6% Si)',
      Coating: 'AZ-150 gsm',
      Thickness: '0.50 mm',
      Width: 'Customizable',
      Standards: 'IS 15965 / ASTM A792',
    },
    imageUrl: '/images/products/roofing-darkblue.jpg',
  },
  {
    id: 'prod-aluzinc',
    name: 'SSN Aluzinc Premium Roofing Sheet (Misted Green)',
    slug: 'ssn-aluzinc-premium',
    category: 'roofing-sheets',
    categoryName: 'Premium Roofing Sheets',
    description: 'High-tensile zinc-aluminium alloy coated steel sheet offering superior corrosion resistance and heat reflectivity.',
    specs: {
      Material: 'Aluminium-Zinc Alloy Coated Steel (55% Al, 43.4% Zn, 1.6% Si)',
      Coating: 'AZ-150 gsm',
      Thickness: '0.50 mm',
      Width: 'Customizable',
      Standards: 'IS 15965 / ASTM A792',
    },
    imageUrl: '/images/products/roofing-green.jpg',
  },
  {
    id: 'prod-ppgi-sheet',
    name: 'SSN Aluzinc Premium Roofing Sheet (Half White)',
    slug: 'ssn-ppgi-sheet',
    category: 'roofing-sheets',
    categoryName: 'Premium Roofing Sheets',
    description: 'High-tensile zinc-aluminium alloy coated steel sheet offering superior corrosion resistance and heat reflectivity.',
    specs: {
      Material: 'Aluminium-Zinc Alloy Coated Steel (55% Al, 43.4% Zn, 1.6% Si)',
      Coating: 'AZ-150 gsm',
      Thickness: '0.50 mm',
      Width: 'Customizable',
      Standards: 'IS 15965 / ASTM A792',
    },
    imageUrl: '/images/products/roofing-white.jpg',
  },
  {
    id: 'prod-galvanized-corrugated',
    name: 'SSN Aluzinc Premium Roofing Sheet (Brick Red)',
    slug: 'ssn-galvanized-corrugated',
    category: 'roofing-sheets',
    categoryName: 'Premium Roofing Sheets',
    description: 'High-tensile zinc-aluminium alloy coated steel sheet offering superior corrosion resistance and heat reflectivity.',
    specs: {
      Material: 'Aluminium-Zinc Alloy Coated Steel (55% Al, 43.4% Zn, 1.6% Si)',
      Coating: 'AZ-150 gsm',
      Thickness: '0.50 mm',
      Width: 'Customizable',
      Standards: 'IS 15965 / ASTM A792',
    },
    imageUrl: '/images/products/roofing-orange.jpg',
  },
  {
    id: 'prod-zinc-pipe',
    name: 'SSN Galvanized Zinc Pipe (GI Pipe)',
    slug: 'ssn-zinc-pipe-gi',
    category: 'zinc-pipes',
    categoryName: 'Zinc Pipes',
    description: 'High durability, zinc-coated galvanized iron pipes providing excellent resistance to rust and industrial fluids.',
    specs: {
      Brands: 'Tata Steel, JSW, Hariom, A1 Gold',
      Grade: 'Class B / Class C',
      Diameter: '15mm to 150mm',
      Coating: '360 gsm pure Zinc Coating',
      Length: '20 Feet (6.0 Meters)',
      Standards: 'IS 1239 / IS 3589',
    },
    imageUrl: '/images/gallery/steel-pipes.jpg',
  },
  {
    id: 'prod-ms-pipe',
    name: 'SSN Mild Steel Black Pipe (MS Pipe)',
    slug: 'ssn-ms-pipe',
    category: 'ms-pipes',
    categoryName: 'MS Pipes',
    description: 'Industrial grade hollow round MS pipes designed for structural fabrications, fluid transit, and structural bracing.',
    specs: {
      Grade: 'YST 210 / YST 240 / YST 310',
      Diameter: '20mm to 200mm',
      Thickness: '1.2 mm, 1.4 mm, 1.6 mm, 2.0 mm',
      Length: '20 Feet (6.0 Meters)',
      Standards: 'IS 1161 / IS 3589',
    },
    imageUrl: '/images/gallery/square-pipes.jpg',
  },
  {
    id: 'prod-ibeam',
    name: 'SSN Universal I-Beam',
    slug: 'ssn-universal-i-beam',
    category: 'structural-steel',
    categoryName: 'Structural Steel',
    description: 'Hot rolled steel structural beam designed to support heavy structural cross-loads.',
    specs: {
      Grade: 'E250BR / E350BR',
      'Flange Width': '100 mm to 250 mm',
      Weight: '11.5 kg/m to 122 kg/m',
      Depth: '116 mm to 600 mm',
      Standards: 'IS 2062 / IS 808',
    },
    imageUrl: '/images/products/structural-steel.jpg',
  },
  {
    id: 'prod-tmt',
    name: 'SSN TMT RODS',
    slug: 'ssn-tmt-fe-550d',
    category: 'tmt-bars',
    categoryName: 'TMT Bars',
    description: 'High ductility thermo-mechanically treated reinforcement bar ideal for earthquake-resistant structures.',
    specs: {
      Grade: 'Fe 550D',
      Diameters: '4 mm, 6 mm, 7 mm, 8 mm, 10 mm, 12 mm, 16 mm, 20 mm, 25 mm',
      Length: 'Customizable',
      Composition: 'Low Carbon, Low Sulphur & Phosphorus',
      Standards: 'IS 1786',
    },
    imageUrl: '/images/gallery/tmt-rebars.jpg',
  },
  {
    id: 'prod-upvc',
    name: 'SSN 3-Layer Corrugated UPVC Sheet',
    slug: 'ssn-3-layer-upvc',
    category: 'upvc-roofing',
    categoryName: 'UPVC Roofing',
    description: 'Co-extruded three-layer UPVC roofing sheet providing excellent sound dampening and anti-corrosion properties.',
    specs: {
      Structure: '3-Layer Co-extruded (ASA Layer + Thermal Insulation + Base)',
      Thickness: '2.5 mm',
      Width: '1130 mm overall, 1050 mm effective',
      Conductivity: '0.325 W/mK',
      Standards: 'GB/T 13542',
    },
    imageUrl: '/images/products/upvc-roofing.jpg',
  },
];

export const CATEGORIES: Category[] = [
  { slug: 'all', name: 'All Materials', icon: Shield },
  { slug: 'roofing-sheets', name: 'Roofing Sheets', icon: Layers },
  { slug: 'zinc-pipes', name: 'Zinc Pipes', icon: Cylinder },
  { slug: 'ms-pipes', name: 'MS Pipes', icon: Wrench },
  { slug: 'structural-steel', name: 'Structural Steel', icon: Hammer },
  { slug: 'tmt-bars', name: 'TMT Bars', icon: Shield },
  { slug: 'upvc-roofing', name: 'UPVC Roofing', icon: Layers },
];
